# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6038baeb48ca632e82b1de0142d28cbccfa3bf5cd3527465ae1a06d250e71b3e3dd7775b8cfad39d5e34d8c0363437139c1786124776623817df757b8d2690cc

test:
  secret_key_base: fd4d791d26f3a2e6b103a4fd6b141b633eefdd112b897f3a71690a76249667f4ff13000a768f0988d004f6d5cdc5e0ff9c1e1a3d686f863ac197d84e8028297a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
